language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  - MAVEN=3.0.4
  - MAVEN=3.0.5
  - MAVEN=3.1.0
  - MAVEN=3.1.1
  - MAVEN=3.2.1
  - MAVEN=3.2.2
  - MAVEN=3.2.3
  - MAVEN=3.2.5
  - MAVEN=3.3.1
  - MAVEN=3.3.3
  - MAVEN=3.3.9

before_install:
  - mkdir /tmp/maven
  - wget -qO- https://archive.apache.org/dist/maven/maven-3/${MAVEN}/binaries/apache-maven-${MAVEN}-bin.tar.gz | tar xz --strip 1 -C /tmp/maven

install: true

script: /tmp/maven/bin/mvn -V clean install site site:stage
