language: java
sudo: false

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  - MAVEN=3.0.4
  - MAVEN=3.0.5
  - MAVEN=3.1.0
  - MAVEN=3.1.1
  - MAVEN=3.2.1
  - MAVEN=3.2.2
  - MAVEN=3.2.3
  - MAVEN=3.2.5
  - MAVEN=3.3.1
  - MAVEN=3.3.3
  - MAVEN=3.3.9

matrix:
  exclude:
  - jdk: openjdk6
    env: MAVEN=3.3.1
  - jdk: openjdk6
    env: MAVEN=3.3.3
  - jdk: openjdk6
    env: MAVEN=3.3.9

cache:
    directories:
    - $HOME/.m2

install:
  - mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN}
  - ./mvnw --show-version --errors --batch-mode validate dependency:go-offline

before_script:
  - export MAVEN_SKIP_RC=true

script: ./mvnw --show-version clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
